config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root    'static_pages#splash'
    get     '/home',    to: 'static_pages#home'
    get     '/help',    to: 'static_pages#help'
    get     '/about',   to: 'static_pages#about'
    get     '/signup',  to: 'users#new'
    post    '/signup',  to: 'users#create'
    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'
    delete  '/logout',  to: 'sessions#destroy'
    get     '/test/:category',  to: 'answers#test', as: 'test'
    post    '/test/:category',  to: 'answers#submitword', as: 'submitword'
    get     '/learners',    to: 'users#index'
    resources :users
    resources :words do
        collection do
            get '/vocabulary', :to => 'words#show', :as => 'dictionary'
            get '/vocabulary/:letter', :to => 'words#index', :as => 'vocabulary'
            get '/greetings', :to => 'words#greetings', :as => 'greetings'
            get '/questions', :to => 'words#questions', :as => 'questions'
            get '/calendar', :to => 'words#calendar', :as => 'calendar'
            get '/numbers', :to => 'words#numbers', :as => 'numbers'
        end
    end
    match '*path' => redirect('/'), via: :get
end

app/models/user.rb
class User < ApplicationRecord
    has_many :answers

    attr_accessor :remember_token

    before_save { self.username = username.downcase }

    VALID_NAME_REGEX = /\A[a-zàâçéèêëîïôûùüÿñæœ ,.'-]+\z/i
    validates :name, presence: true, length: { maximum: 50 },
                    format: { with: VALID_NAME_REGEX }

    # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_USERNAME_REGEX = /\A[a-z0-9\-_.]+\z/i
    validates :username, presence: true, length: { maximum: 50 },
                    format: { with: VALID_USERNAME_REGEX },
                    uniqueness: { case_sensitive: false }

    validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

    has_secure_password

    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
    before_action :correct_user,   only: [:edit, :update]
    before_action :logged_out_user, only: [:new]
    before_action :admin_user,     only: [:destroy]

    def index
        @users = User.paginate(page: params[:page], :per_page => 15).order('name ASC')
    end

    def show
        @user = User.find(params[:id])
        rescue ActiveRecord::RecordNotFound
            redirect_to root_url
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:success] = "Welcome to Learn Language!"
            redirect_to home_url
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:success] = "Profile updated!"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:success] = "User deleted"
        redirect_to users_url
    end

    private

        def user_params
          params.require(:user).permit(:name, :username, :password,
                                       :password_confirmation)
        end

        # Before filters

        # Confirms the correct user.
        def correct_user
            @user = User.find(params[:id])
            redirect_to(root_url) unless (current_user?(@user) || current_user.admin?)
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<tr>
    <td>
        <span class="user-icon">
            <i class="fa fa-user-circle-o fa-fw fa-3x" aria-hidden="true"></i>
        </span>
        <%= link_to user.name, user, class: 'user-link' %>
        <span class="text-muted"><%= user.username %></span>
    </td>
    <td>
        <%= user.created_at.strftime("%A, %B #{user.created_at.day.ordinalize}, %Y") %>
    </td>
    <td>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= user_answers_percentage(user) %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= user_answers_percentage(user) %>%;">
                <span class="sr-only"><%= user_answers_percentage(user) %>% Complete</span>
            </div>
            <span class="progress-completed"><%= user_answers_percentage(user) %>%</span>
        </div>
    </td>
    <td>
        <div class="pull-right">
            <% if current_user.admin? && !current_user?(user) %>
                <%= button_to "Delete", user, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-primary' %>
            <% end %>
        </div>
    </td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "My Profile") %>
<div class="page-header">
    <h1>My Profile</h1>
</div>
<div class="edit-profile app-form box-shadow">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-input form-control form-line", placeholder: "Name" %>
        </div>

        <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, class: "form-input form-control form-line", placeholder: "Username" %>
        </div>

        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-input form-control form-line", placeholder: "Password" %>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-input form-control form-line", placeholder: "Confirmation" %>
        </div>

        <%= f.submit "Save", class: "btn btn-primary form-line" %>
    <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, "Learners") %>
<div class="page-header">
    <h1>Learners</h1>
</div>

<%= render 'shared/flash' %>

<%= will_paginate %>

<div class="table-responsive box-shadow">
    <table class="table table-hover users-table">
        <thead>
            <tr>
                <th class="col-md-3">Name</th>
                <th class="col-md-3">Joined on</th>
                <th class="col-md-5">Learning Progress</th>
                <th class=""></th>
            </tr>
        </thead>
        <tbody>
            <%= render @users %>
        </tbody>
    </table>
</div>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<% content_for :body_class, 'splash' %>
<% content_for :main_style, 'margin:0;' %>
<% content_for :sidemenu_class, 'hidden-sm hidden-md hidden-lg' %>

<%= form_for(@user, url: signup_path, :html => { :class => "app-form login-register-form box-shadow"} ) do |f| %>
    <h1>Sign Up</h1>
    <%= render 'shared/error_messages' %>

    <%= f.text_field :name, class: "form-input form-control form-line", placeholder: "Name", autofocus: true %>

    <%= f.text_field :username, class: "form-input form-control form-line", placeholder: "Username"  %>

    <%= f.password_field :password, class: "form-input form-control form-line", placeholder: "Password" %>

    <%= f.password_field :password_confirmation, class: "form-input form-control form-line", placeholder: "Confirmation" %>

    <%= f.submit "Create", class: "btn btn-primary form-line" %>

    <p class="message">Already registered? <%= link_to "Log In", login_path %></p>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="page-header">
    <h1>
        <%= @user.name %>
        <% if current_user?(@user) || current_user.admin? %>
            <div class="pull-right">
                <%= link_to edit_user_path(@user), class: "btn", :action => 'go' do %>
                    Edit Profile
                <% end %>
            </div>
        <% end %>
    </h1>
</div>

<%= render 'shared/flash' %>

<div class="text-muted">
    Joined on <%= @user.created_at.strftime("%A, %B #{@user.created_at.day.ordinalize}, %Y") %>
</div>

<br/>

<div class="col-md-4">
    <h3>Learning Progress</h3>
    <div class="box-shadow">
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= user_answers_percentage_by_type(@user, 'Greetings') %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= user_answers_percentage_by_type(@user, 'Greetings') %>%;">
                <span class="sr-only"><%= user_answers_percentage_by_type(@user, 'Greetings') %>% Complete</span>
            </div>
            <span class="progress-type">Greetings</span>
            <span class="progress-completed"><%= user_answers_percentage_by_type(@user, 'Greetings') %>%</span>
        </div>

        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= user_answers_percentage_by_type(@user, 'Questions') %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= user_answers_percentage_by_type(@user, 'Questions') %>%;">
                <span class="sr-only"><%= user_answers_percentage_by_type(@user, 'Questions') %>% Complete</span>
            </div>
            <span class="progress-type">Questions</span>
            <span class="progress-completed"><%= user_answers_percentage_by_type(@user, 'Questions') %>%</span>
        </div>

        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= user_answers_percentage_by_type(@user, 'Calendar') %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= user_answers_percentage_by_type(@user, 'Calendar') %>%;">
                <span class="sr-only"><%= user_answers_percentage_by_type(@user, 'Calendar') %>% Complete</span>
            </div>
            <span class="progress-type">Calendar</span>
            <span class="progress-completed"><%= user_answers_percentage_by_type(@user, 'Calendar') %>%</span>
        </div>

        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= user_answers_percentage_by_type(@user, 'Numbers') %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= user_answers_percentage_by_type(@user, 'Numbers') %>%;">
                <span class="sr-only"><%= user_answers_percentage_by_type(@user, 'Numbers') %>% Complete</span>
            </div>
            <span class="progress-type">Numbers</span>
            <span class="progress-completed"><%= user_answers_percentage_by_type(@user, 'Numbers') %>%</span>
        </div>

        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= user_answers_percentage_by_type(@user, 'Vocabulary') %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= user_answers_percentage_by_type(@user, 'Vocabulary') %>%;">
                <span class="sr-only"><%= user_answers_percentage_by_type(@user, 'Vocabulary') %>% Complete</span>
            </div>
            <span class="progress-type">Vocabulary</span>
            <span class="progress-completed"><%= user_answers_percentage_by_type(@user, 'Vocabulary') %>%</span>
        </div>
    </div>
</div>