config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root    'static_pages#splash'
    get     '/home',    to: 'static_pages#home'
    get     '/help',    to: 'static_pages#help'
    get     '/about',   to: 'static_pages#about'
    get     '/signup',  to: 'users#new'
    post    '/signup',  to: 'users#create'
    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'
    delete  '/logout',  to: 'sessions#destroy'
    get     '/test/:category',  to: 'answers#test', as: 'test'
    post    '/test/:category',  to: 'answers#submitword', as: 'submitword'
    get     '/learners',    to: 'users#index'
    resources :users
    resources :words do
        collection do
            get '/vocabulary', :to => 'words#show', :as => 'dictionary'
            get '/vocabulary/:letter', :to => 'words#index', :as => 'vocabulary'
            get '/greetings', :to => 'words#greetings', :as => 'greetings'
            get '/questions', :to => 'words#questions', :as => 'questions'
            get '/calendar', :to => 'words#calendar', :as => 'calendar'
            get '/numbers', :to => 'words#numbers', :as => 'numbers'
        end
    end
    match '*path' => redirect('/'), via: :get
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :word
  validates_uniqueness_of :user_id, :scope => :word_id
end

app/controllers/answers_controller.rb
require "i18n"

class AnswersController < ApplicationController
    before_action :logged_in_user

    def test
        @word_answer = Answer.new
        @categories = Category.all.collect{|category| category.name}
        if params[:category] && @categories.any? && @categories.include?(params[:category])
            @category = params[:category]
            @progress_percentage = user_answers_percentage_by_type(current_user, @category)
            word = nil
            if @progress_percentage == 100
                word = Word.joins(:category).where(categories: {name: @category}).order("RANDOM()").first
            else
                word = Word.joins(:category).where(categories: {name: @category}).where.not(id: Answer.where(user_id: current_user.id).select(:word_id)).order("RANDOM()").first
            end
            if word.nil?
                flash[:danger] = "No word found :("
                redirect_to home_url
            else
                @word_answer.word_id = word.id
                @word_answer.english = (word.english_prefix ? word.english_prefix + ' ' : '') + word.english
            end
        else
            flash[:danger] = "No word found :("
            redirect_to home_url
        end
    end

    def submitword
        @word_answer = Answer.new(answer_params)
        @dictionary_word = Word.find_by_id(@word_answer.word_id)
        if @dictionary_word && @word_answer && defined?(@word_answer.spanish) && I18n.transliterate(@word_answer.spanish.downcase) == I18n.transliterate(@dictionary_word.spanish.downcase)
            @word_answer.user_id = current_user.id
            @word_answer.save
            redirect_to test_path(params[:category])
        else
            flash[:danger] = "Incorrect answer. Try this word:"
            redirect_to test_path(params[:category])
        end
    end

    private
        def answer_params
            params.require(:answer).permit(:word_id, :english, :spanish)
        end
end

app/helpers/answers_helper.rb
module AnswersHelper
    def user_answers_percentage(user)
        total = Word.count
        if total == 0
            total = 1
        end
        @user_answers_percentage = (Answer.where(user_id: user.id).count.to_f / total * 100).to_i
    end

    def user_answers_percentage_by_type(user, type)
        total = Word.joins(:category).where(categories: {name: type} ).count
        if total == 0
            total = 1
        end
        @user_answers_percentage_by_type = (
            Answer.joins(:word => :category).where(:user_id => user.id, :categories => {:name => type}).count.to_f / total * 100
        ).to_i
    end
end

app/views/answers/test.html.erb
<% provide(:title, "¿Cómo se dice en español?") %>
<div class="page-header">
    <h1>
        ¿Cómo se dice en español?
    </h1>
</div>

<%= form_for(@word_answer, url: submitword_path, :html => { :class => "app-form new-word-container new-word-form box-shadow" } ) do |f| %>
    <div>
        <%= render 'shared/flash' %>
        <h2><%= @word_answer.english %></h2>
    </div>
    <%= render 'shared/error_messages' %>
    <div class="form-group">
        <%= f.hidden_field :word_id, :value => @word_answer.word_id %>
        <%= f.hidden_field :english, :value => @word_answer.english %>
        <%= f.text_field :spanish, class: "form-input form-control", autofocus: true %>
    </div>
    <div class="row test-button-group">
        <div class="pull-right">
            <%= f.submit "Next", class: "btn btn-primary" %>
            <%= link_to "Skip", test_path(@category), class: "btn" %>
        </div>
    </div>
<% end %>

<div class="new-word-container">
    <div class="alert alert-info">
        It does not take account of accents and it's not case-sensitive.
    </div>
    <% if @progress_percentage == 100 %>
        <div class="alert alert-success">
            Congratulations! You've completed this section. You can still practice.
        </div>
    <% end %>
</div>