config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root    'static_pages#splash'
    get     '/home',    to: 'static_pages#home'
    get     '/help',    to: 'static_pages#help'
    get     '/about',   to: 'static_pages#about'
    get     '/signup',  to: 'users#new'
    post    '/signup',  to: 'users#create'
    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'
    delete  '/logout',  to: 'sessions#destroy'
    get     '/test/:category',  to: 'answers#test', as: 'test'
    post    '/test/:category',  to: 'answers#submitword', as: 'submitword'
    get     '/learners',    to: 'users#index'
    resources :users
    resources :words do
        collection do
            get '/vocabulary', :to => 'words#show', :as => 'dictionary'
            get '/vocabulary/:letter', :to => 'words#index', :as => 'vocabulary'
            get '/greetings', :to => 'words#greetings', :as => 'greetings'
            get '/questions', :to => 'words#questions', :as => 'questions'
            get '/calendar', :to => 'words#calendar', :as => 'calendar'
            get '/numbers', :to => 'words#numbers', :as => 'numbers'
        end
    end
    match '*path' => redirect('/'), via: :get
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  validates :english, presence: true, uniqueness: { case_sensitive: false }
  validates :spanish, presence: true
  validates :category_id, presence: true
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
    before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
    before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy]

    def index
        @first_letters = Word.joins(:category).where(categories: {name: 'Vocabulary'}).order(:english).collect{|word| word.english[0,1].upcase}.uniq.sort
        if params[:letter] && @first_letters.any? && @first_letters.include?(params[:letter])
            letter = params[:letter] + '%'
            @words = Word.joins(:category).where.has {(category.name == 'Vocabulary') & (english =~ letter)}.ordering { [english.asc] }
        else
            redirect_to dictionary_words_url
        end
    end

    def show
        @first_letters = Word.joins(:category).where(categories: {name: 'Vocabulary'}).order(:english).collect{|word| word.english[0,1].upcase}.uniq.sort
        if @first_letters.any?
            redirect_to vocabulary_words_url(@first_letters.first)
        else
            flash[:danger] = "No words in the dictionary :("
            redirect_to home_url
        end
    end

    def greetings
        @words = Word.joins(:category).where(categories: {name: 'Greetings'} )
    end

    def questions
        @words = Word.joins(:category).where(categories: {name: 'Questions'} )
    end

    def calendar
        @month_words = Word.joins(:category).where(categories: {name: 'Calendar'}, tag: 'month')
        @day_words = Word.joins(:category).where(categories: {name: 'Calendar'}, tag: 'day')
        @period_words = Word.joins(:category).where(categories: {name: 'Calendar'}, tag: 'period' )
    end

    def numbers
        @words1 = Word.joins(:category).where(categories: {name: 'Numbers'}, tag: '1')
        @words2 = Word.joins(:category).where(categories: {name: 'Numbers'}, tag: '2')
        @words3 = Word.joins(:category).where(categories: {name: 'Numbers'}, tag: '3')
        @words4 = Word.joins(:category).where(categories: {name: 'Numbers'}, tag: '4')
        @words5 = Word.joins(:category).where(categories: {name: 'Numbers'}, tag: '5')
        @words6 = Word.joins(:category).where(categories: {name: 'Numbers'}, tag: '6')
    end

    def new
        @word = Word.new
    end

    def create
        @word = Word.new(word_params)
        if @word.save
            flash[:success] = "New word succesfully added!"
            redirect_to home_url
        else
            render 'new'
        end
    end

    def edit
        @word = Word.find(params[:id])
    end

    def update
        @word = Word.find(params[:id])
        if @word.update_attributes(word_params)
            flash[:success] = "Word updated!"
            redirect_to @word
        else
            render 'edit'
        end
    end

    def destroy
        Word.find(params[:id]).destroy
        flash[:success] = "Word deleted"
        redirect_to dictionary_words_url
    end

    private

        def word_params
          params.require(:word).permit(:english, :english_prefix, :spanish, :category_id, :tag)
        end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_words_table.html.erb
<div class="table-responsive box-shadow">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="col-xs-<%= defined?(en_col_size) ? en_col_size : 6 %>">English</th>
                <th class="col-xs-<%= defined?(en_col_size) ? es_col_size : 6 %>">Español</th>
            </tr>
        </thead>
        <tbody>
            <% words.each do |word| %>
                <tr>
                    <td>
                        <% if word.english_prefix %><%= word.english_prefix %> <% end %>
                        <%= word.english %>
                    </td>
                    <td>
                        <%= word.spanish %>
                        <% if logged_in? && current_user.admin? %>
                            <div class="pull-right">
                                <%= link_to word, method: :delete, data: { confirm: "Are you sure?" }, :class => 'no-hover-style', :action => 'go' do %>
                                    <i class="fa fa-trash fa-fw" aria-hidden="true"></i>
                                <% end %>
                                <%= link_to edit_word_path(word), :class => 'no-hover-style', :action => 'go' do %>
                                    <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>
                                <% end %>
                            </div>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/words/calendar.html.erb
<% provide(:title, "Calendar") %>
<div class="page-header">
    <h1>
        Calendar
        <% if logged_in? %>
            <div class="pull-right">
                <%= link_to "Start Practice", test_path("Calendar"), class: "btn btn-primary" %>
            </div>
        <% end %>
    </h1>
</div>

<%= render 'shared/flash' %>

<div class="col-xs-12 col-md-6 col-md-offset-3">
    <h3>Months</h3>
    <%= render 'words/words_table', :words => @month_words %>
</div>

<div class="col-xs-12 col-md-6 col-md-offset-3">
    <h3>Week Days</h3>
    <%= render 'words/words_table', :words => @day_words %>
</div>

<div class="col-xs-12 col-md-6 col-md-offset-3">
    <h3>Day Periods</h3>
    <%= render 'words/words_table', :words => @period_words %>
</div>

app/views/words/edit.html.erb
<% provide(:title, "Edit Word") %>
<div class="page-header">
    <h1>Edit Word</h1>
</div>

<%= render 'shared/flash' %>

<div class="word-form app-form box-shadow">
    <%= form_for(@word) do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
            <%= f.label :english %>
            <%= f.text_field :english, class: "form-input form-control form-line", placeholder: "English Word" %>
        </div>

        <div class="form-group">
            <%= f.label :english_prefix %>
            <%= f.text_field :english_prefix, class: "form-input form-control form-line", placeholder: "English Prefix" %>
        </div>

        <div class="form-group">
            <%= f.label :spanish %>
            <%= f.text_field :spanish, class: "form-input form-control form-line", placeholder: "Spanish Word" %>
        </div>

        <div class="form-group">
            <%= f.label :category_id %>
            <%= f.collection_select :category_id, Category.order(:name), :id, :name, {}, {class: "form-control form-line"} %>
        </div>

        <div class="form-group">
            <%= f.label :tag %>
            <%= f.text_field :tag, class: "form-input form-control form-line", placeholder: "Tag" %>
        </div>

        <%= f.submit "Save", class: "btn btn-primary form-line" %>
    <% end %>
</div>

app/views/words/greetings.html.erb
<% provide(:title, "Greetings") %>
<div class="page-header">
    <h1>
        Greetings
        <% if logged_in? %>
            <div class="pull-right">
                <%= link_to "Start Practice", test_path("Greetings"), class: "btn btn-primary" %>
            </div>
        <% end %>
    </h1>
</div>

<%= render 'shared/flash' %>

<div class="col-xs-12 col-md-6 col-md-offset-3">
    <%= render 'words/words_table', :words => @words %>
</div>

app/views/words/index.html.erb
<% provide(:title, "Vocabulary") %>
<div class="page-header">
    <h1>
        Vocabulary
        <% if logged_in? %>
            <div class="pull-right">
                <%= link_to "Start Practice", test_path("Vocabulary"), class: "btn btn-primary" %>
            </div>
        <% end %>
    </h1>
</div>

<%= render 'shared/flash' %>

<% if !@first_letters.nil? %>
    <div class="alpha-pagination">
        <ul class="pagination">
            <% @first_letters.each do |letter| %>
                <li class="<%= active_class(vocabulary_words_path(letter)) %>">
                    <%= active_link_to "#{letter}", vocabulary_words_path(letter) %>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="col-xs-12 col-md-6 col-md-offset-3">
    <%= render 'words/words_table', :words => @words %>
</div>

app/views/words/new.html.erb
<% provide(:title, "Add Word") %>
<div class="page-header">
    <h1>Add Word</h1>
</div>

<%= render 'shared/flash' %>

<div class="word-form app-form box-shadow">
    <%= form_for(@word) do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
            <%= f.label :english %>
            <%= f.text_field :english, class: "form-input form-control form-line", placeholder: "English Word", autofocus: true %>
        </div>

        <div class="form-group">
            <%= f.label :english_prefix %>
            <%= f.text_field :english_prefix, class: "form-input form-control form-line", placeholder: "English Prefix" %>
        </div>

        <div class="form-group">
            <%= f.label :spanish %>
            <%= f.text_field :spanish, class: "form-input form-control form-line", placeholder: "Spanish Word" %>
        </div>

        <div class="form-group">
            <%= f.label :category_id %>
            <%= f.collection_select :category_id, Category.order(:name), :id, :name, {prompt: "Select a category"}, {class: "form-control form-line"} %>
        </div>

        <div class="form-group">
            <%= f.label :tag %>
            <%= f.text_field :tag, class: "form-input form-control form-line", placeholder: "Tag" %>
        </div>

        <%= f.submit "Save", class: "btn btn-primary form-line" %>
    <% end %>
</div>

app/views/words/numbers.html.erb
<% provide(:title, "Numbers") %>
<div class="page-header">
    <h1>
        Numbers
        <% if logged_in? %>
            <div class="pull-right">
                <%= link_to "Start Practice", test_path("Numbers"), class: "btn btn-primary" %>
            </div>
        <% end %>
    </h1>
</div>

<%= render 'shared/flash' %>

<div class="col-xs-12 col-sm-6 col-md-4 box-container">
    <%= render 'words/words_table', :en_col_size => '4', :es_col_size => '8', :words => @words1 %>
</div>

<div class="col-xs-12 col-sm-6 col-md-4 box-container">
    <%= render 'words/words_table', :en_col_size => '4', :es_col_size => '8', :words => @words2 %>
</div>

<div class="col-xs-12 col-sm-6 col-md-4 box-container">
    <%= render 'words/words_table', :en_col_size => '4', :es_col_size => '8', :words => @words3 %>
</div>

<div class="col-xs-12 col-sm-6 col-md-4 box-container">
    <%= render 'words/words_table', :en_col_size => '4', :es_col_size => '8', :words => @words4 %>
</div>

<div class="col-xs-12 col-sm-6 col-md-4 box-container">
    <%= render 'words/words_table', :en_col_size => '4', :es_col_size => '8', :words => @words5 %>
</div>

<div class="col-xs-12 col-sm-6 col-md-4 box-container">
    <%= render 'words/words_table', :en_col_size => '4', :es_col_size => '8', :words => @words6 %>
</div>

app/views/words/questions.html.erb
<% provide(:title, "Questions") %>
<div class="page-header">
    <h1>
        Questions
        <% if logged_in? %>
            <div class="pull-right">
                <%= link_to "Start Practice", test_path("Questions"), class: "btn btn-primary" %>
            </div>
        <% end %>
    </h1>
</div>

<%= render 'shared/flash' %>

<div class="col-xs-12 col-md-6 col-md-offset-3">
    <%= render 'words/words_table', :words => @words %>
</div>