config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root    'static_pages#splash'
    get     '/home',    to: 'static_pages#home'
    get     '/help',    to: 'static_pages#help'
    get     '/about',   to: 'static_pages#about'
    get     '/signup',  to: 'users#new'
    post    '/signup',  to: 'users#create'
    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'
    delete  '/logout',  to: 'sessions#destroy'
    get     '/test/:category',  to: 'answers#test', as: 'test'
    post    '/test/:category',  to: 'answers#submitword', as: 'submitword'
    get     '/learners',    to: 'users#index'
    resources :users
    resources :words do
        collection do
            get '/vocabulary', :to => 'words#show', :as => 'dictionary'
            get '/vocabulary/:letter', :to => 'words#index', :as => 'vocabulary'
            get '/greetings', :to => 'words#greetings', :as => 'greetings'
            get '/questions', :to => 'words#questions', :as => 'questions'
            get '/calendar', :to => 'words#calendar', :as => 'calendar'
            get '/numbers', :to => 'words#numbers', :as => 'numbers'
        end
    end
    match '*path' => redirect('/'), via: :get
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
            Website built by <a href="http://www.kimsangly.com">Kim Sang Ly</a>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <%= render 'layouts/top_menu' %>
    </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
    <![endif]-->

app/views/layouts/_side_menu.html.erb
<div class="<%= content_for :sidemenu_class %>">
    <nav class="sidebar collapse" role="navigation" id="side-menu">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav">
                <li>
                    <%= active_link_to greetings_words_path, :action => 'go' do %>
                        <div class="icon"><i class="fa fa-handshake-o fa-fw" aria-hidden="true"></i></div>
                        <div class="title">Greetings</div>
                    <% end %>
                </li>
                <li>
                    <%= active_link_to questions_words_path, :action => 'go' do %>
                        <div class="icon"><i class="fa fa-question fa-fw" aria-hidden="true"></i></div>
                        <div class="title">Questions</div>
                    <% end %>
                </li>
                <li>
                    <%= active_link_to calendar_words_path, :action => 'go' do %>
                        <div class="icon"><i class="fa fa-calendar-o fa-fw" aria-hidden="true"></i></div>
                        <div class="title">Calendar</div>
                    <% end %>
                </li>
                <li>
                    <%= active_link_to numbers_words_path, :action => 'go' do %>
                        <div class="icon"><i class="fa fa-list-ol fa-fw" aria-hidden="true"></i></div>
                        <div class="title">Numbers</div>
                    <% end %>
                </li>
                <li>
                    <%= active_link_to dictionary_words_path, :action => 'go' do %>
                        <div class="icon"><i class="fa fa-book fa-fw" aria-hidden="true"></i></div>
                        <div class="title">Other Vocabulary</div>
                    <% end %>
                </li>
                <li class="hidden-sm hidden-md hidden-lg">
                    <%= active_link_to about_path, :action => 'go' do %>
                        <div class="icon"><i class="fa fa-info fa-fw" aria-hidden="true"></i></div>
                        <div class="title">About</div>
                    <% end %>
                </li>
                <% if logged_in? %>
                    <% if current_user.admin? %>
                        <li >
                            <%= active_link_to new_word_path, :action => 'go' do %>
                                <div class="icon"><i class="fa fa-pencil fa-fw" aria-hidden="true"></i></div>
                                <div class="title">Add Word</div>
                            <% end %>
                        </li>
                    <% end %>
                    <li class="hidden-sm hidden-md hidden-lg">
                        <%= active_link_to learners_path, :action => 'go' do %>
                            <div class="icon"><i class="fa fa-users fa-fw" aria-hidden="true"></i></div>
                            <div class="title">Learners</div>
                        <% end %>
                    </li>
                    <li class="hidden-sm hidden-md hidden-lg">
                        <%= active_link_to user_path(@current_user), :action => 'go' do %>
                            <div class="icon"><i class="fa fa-user-circle-o fa-fw" aria-hidden="true"></i></div>
                            <div class="title"><%= @current_user.name %></div>
                        <% end %>
                    </li>
                    <li class="hidden-sm hidden-md hidden-lg">
                        <%= active_link_to logout_path, method: "delete", :action => 'go' do %>
                            <div class="icon"><i class="fa fa-sign-out fa-fw" aria-hidden="true"></i></div>
                            <div class="title">Log Out</div>
                        <% end %>
                    </li>
                <% else %>
                    <li class="hidden-sm hidden-md hidden-lg">
                        <%= active_link_to login_path, :action => 'go' do %>
                            <div class="icon"><i class="fa fa-sign-in fa-fw" aria-hidden="true"></i></div>
                            <div class="title">Log In</div>
                        <% end %>
                    </li>
                    <li class="hidden-sm hidden-md hidden-lg">
                        <%= active_link_to signup_path, :action => 'go' do %>
                            <div class="icon"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i></div>
                            <div class="title">Sign Up</div>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/_top_menu.html.erb
<div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#side-menu">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <% if logged_in? %>
            <%= link_to "Learn Language - Spanish", home_path, id: "logo", class: "navbar-brand" %>
        <% else %>
            <%= link_to "Learn Language - Spanish", root_path, id: "logo", class: "navbar-brand" %>
        <% end %>
    </div>

    <nav class="navbar-right hidden-xs">
        <ul class="nav navbar-nav">
            <li>
                <%= link_to "About", about_path %>
            </li>
            <% if logged_in? %>
                <li>
                    <%= link_to learners_path, :action => 'go' do %>
                        <i class="fa fa-users fa-fw" aria-hidden="true"></i> Learners
                    <% end %>
                </li>
                <li>
                    <%= link_to user_path(@current_user), :action => 'go' do %>
                        <i class="fa fa-user-circle-o fa-fw" aria-hidden="true"></i> <%= @current_user.name %>
                    <% end %>
                </li>
                <li>
                    <%= link_to logout_path, method: "delete", :action => 'go' do %>
                        <i class="fa fa-sign-out fa-fw" aria-hidden="true"></i> Log Out
                    <% end %>
                </li>
            <% else %>
                <li>
                    <%= link_to "Log In", login_path %>
                </li>
                <li>
                    <%= link_to "Sign Up", signup_path %>
                </li>
            <% end %>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Learn Language - Spanish Vocabulary">
        <meta name="author" content="Kim Sang Ly">
        <title><%= full_title(yield(:title)) %></title>
        <%= render 'layouts/rails_default' %>
        <%= render 'layouts/shim' %>
    </head>

    <body class="<%= content_for :body_class %>">
        <div class="page-wrapper">
            <%= render 'layouts/header' %>
            <%= render 'layouts/side_menu' %>
            <div class="main" style="<%= content_for :main_style %>">
                <div class="container-fluid">
                    <%= yield %>
                </div>
            </div>
        </div>
        <%= debug(params) if Rails.env.development? %>
    </body>
</html>